
---

- name: download WordPress
  get_url:
    url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    dest: "{{ wordpress_install_src_dir }}/wordpress-{{ wordpress_version }}.tar.gz"

- name: unpack WordPress
  unarchive:
    src: "{{ wordpress_install_src_dir }}/wordpress-{{ wordpress_version }}.tar.gz"
    dest: "{{ wordpress_install_src_dir }}"
    remote_src: yes

