---

# TBD: ansible mysql module has issue to set the root password, this is the temp workaroud
#- name: set mysql root password 
#  shell: mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('{{ root_db_pass }}') WHERE User='root';"
#  ignore_errors: yes

- name: set mysql root password 
  shell: mysqladmin -u root password {{ root_db_pass }}
  ignore_errors: yes


- name: Create WordPress database
  mysql_db: 
    name: "{{ wp_db_name }}"
    state: present    
    login_user: root
    login_password: "{{ root_db_pass }}"
    
- name: Create WordPress database user
  mysql_user: 
    name: "{{ wp_db_user }}" 
    password: "{{ wp_db_password }}" 
    priv: "{{ wp_db_name }}.*:ALL" 
    host: localhost 
    state: present
    login_user: root
    login_password: "{{ root_db_pass }}"

- name: Create WordPress database user
  mysql_user: 
    name: "{{ wp_db_user }}" 
    password: "{{ wp_db_password }}" 
    priv: "{{ wp_db_name }}.*:ALL" 
    host: "{{  web_server_ip }}" 
    state: present
    login_user: root
    login_password: "{{ root_db_pass }}"

- name: restart mysql Service
  service: 
    name: mysqld 
    state: restarted 
  become: yes
  become_user: root
