---

- name: install mysql
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
     - mysql
     - mysql-server
#    - mariadb-server
#    - mariadb
  become: yes
  become_user: root

- name: install MySQL-python
  yum: 
    name: MySQL-python
    state: present
  become: yes
  become_user: root

- name: start mysql
  service:
    name: mysqld
    state: started
    enabled: yes
  become: yes
  become_user: root
