---

- name: install mariadbs
  yum: 
    name: {{ item }}
    state: latest
  with_items:
    - mariadb-server
    - mariadb

- name: Start mariadb Service
  service: 
    name=mariadb 
    state=started 
    enabled=yes
