---

- name: install mariadbs
  yum: 
    name: "{{ item }}-{{ mariadb_verion }}"
    state: present
  with_items:
    - mariadb-server
    - mariadb
  become: yes
  become_user: root

- name: install MySQL-python
  yum: 
    name: MySQL-python-1.2.5
    state: present
  become: yes
  become_user: root

- name: start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes
  become_user: root
