---
AWSTemplateFormatVersion: 2010-09-09
Description: top level template to compose other nested templates to form a two tiered subnet wordpress application

Parameters:
  pKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the web tier
    Type: AWS::EC2::KeyPair::KeyName
    Default: cl-key-1
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    AllowedPattern: ".+"

  pInstanceType: 
    Description: EC2 InstanceType.
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small

Resources:
  rTwoTierVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cl-stack/two-tier-network-stack.yml
      TimeoutInMinutes: '5'
  
  rWebEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pKeyName: !Ref pKeyName
        pInstanceType: !Ref pInstanceType
        pSubnet: !Sub ${rTwoTierVPCStack.Outputs.oPubSubnet}
        pSecurityGroup: !Sub ${rTwoTierVPCStack.Outputs.oPubSubnetSecurityGroup}
      TemplateURL: https://s3.amazonaws.com/cl-stack/web-ec2-stack.yml
      TimeoutInMinutes: '5'
