---
AWSTemplateFormatVersion: 2010-09-09
Description: Web EC2 instance attached with subnet and security group

Parameters:
  
  pKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the gettance
    Type: AWS::EC2::KeyPair::KeyName
    AllowedPattern: ".+"

  pInstanceType: 
    Description: EC2 InstanceType.
    Type: String
    AllowedPattern: ".+"

  pSubnet:
    Description: the subnet the webEc2 is in
    Type: AWS::EC2::Subnet::Id

  pSecurityGroup:
    Description: the security grouip of the subnet
    Type: AWS::EC2::SecurityGroup::Id 

  pBackServerIp:
    Description: The IP of the backend server or LB
    Type: String 


Resources:
  rEC2Web:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref pInstanceType
      KeyName: !Ref pKeyName
      ImageId: ami-467ca739
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref pSecurityGroup
          SubnetId: !Ref pSubnet
      UserData:
        Fn::Base64:                               
          !Sub |
            #!/bin/bash -ex
              yum-config-manager --enable epel 
              
              yum update -y 
              yum install ansible -y
              yum install git -y
              
              git clone https://github.com/kknd22/cloudformation-sample.git
              cd cloudformation-sample
              ansible-playbook -i webs.ini playbook-web.yml --extra-vars "db_server_ip=${pBackServerIp}"
Outputs:
  oWebURL:
    Description: Newly created web home URL      
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - rEC2Web
          - PublicIp



