---

- name: install php and its modules
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - php
    - php-mysql
    - php-gd
  become: yes
  become_user: root

- name: start httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  become: yes
  become_user: root
